name: Hello World Workflow

     on:
       push:
         branches: [ main ]
       pull_request:
         branches: [ main ]

     jobs:

       build:
         runs-on: ubuntu-latest

         steps:
         - uses: actions/checkout@v2
         - name: Run say-hello command
           run: make say-hello